[package]
name = "tokio_retry_simple"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
tokio = { version = "1", features = ["time"] }

[dev-dependencies]
tokio = { version = "1", features = ["time", "test-util", "macros", "rt", "rt-multi-thread"] }
